	tilepal 0, GREEN, ROOF, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF, BROWN, BROWN
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, WATER, ROOF, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN, RED
	tilepal 0, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, ROOF, GRAY, GRAY
	