CinnabarVolcano_Script:
	ret

CinnabarVolcano_TextPointers:
	def_text_pointers
	dw_const BoulderText, TEXT_CINNABARVOLCANO_BOULDER1
	dw_const BoulderText, TEXT_CINNABARVOLCANO_BOULDER2
	dw_const BoulderText, TEXT_CINNABARVOLCANO_BOULDER3
	dw_const BoulderText, TEXT_CINNABARVOLCANO_BOULDER4