SpritePaletteAssignments: ; Characters on the overworld
	table_width 1, SpritePaletteAssignments
	; 0x01: SPRITE_RED
	db SPR_PAL_ORANGE

	; 0x02: SPRITE_BLUE
IF DEF(_BLUE)
	db SPR_PAL_ORANGE
ELSE ; _RED
	db SPR_PAL_BLUE
ENDC

	; 0x03: SPRITE_OAK
	db SPR_PAL_BROWN

	; 0x04: SPRITE_BUG_CATCHER
	db SPR_PAL_RANDOM

	; 0x05: SPRITE_SLOWBRO
	db SPR_PAL_ORANGE

	; 0x06: SPRITE_LASS
	db SPR_PAL_RANDOM

	; 0x07: SPRITE_BLACK_HAIR_BOY_1
	db SPR_PAL_RANDOM

	; 0x08: SPRITE_LITTLE_GIRL
	db SPR_PAL_RANDOM

	; 0x09: SPRITE_BIRD
	db SPR_PAL_ORANGE

	; 0x0a: SPRITE_FAT_BALD_GUY
	db SPR_PAL_RANDOM

	; 0x0b: SPRITE_GAMBLER
	db SPR_PAL_RANDOM

	; 0x0c: SPRITE_BLACK_HAIR_BOY_2
	db SPR_PAL_RANDOM

	; 0x0d: SPRITE_GIRL
	db SPR_PAL_RANDOM

	; 0x0e: SPRITE_HIKER
	db SPR_PAL_RANDOM

	; 0x0f: SPRITE_FOULARD_WOMAN
	db SPR_PAL_RANDOM

	; 0x10: SPRITE_GENTLEMAN
	db SPR_PAL_BLUE

	; 0x11: SPRITE_DAISY
	db SPR_PAL_BLUE

	; 0x12: SPRITE_BIKER
	db SPR_PAL_RANDOM

	; 0x13: SPRITE_SAILOR
	db SPR_PAL_RANDOM

	; 0x14: SPRITE_COOK
	db SPR_PAL_RANDOM

	; 0x15: SPRITE_BIKE_SHOP_GUY
	db SPR_PAL_RANDOM

	; 0x16: SPRITE_MR_FUJI
	db SPR_PAL_GREEN

	; 0x17: SPRITE_GIOVANNI
	db SPR_PAL_BLUE
	
	; 0x+1: SPRITE_BLAINE
	db SPR_PAL_ORANGE
	
	; 0x+2: SPRITE_BROCK
	db SPR_PAL_BROWN
	
	; 0x+3: SPRITE_ERIKA
	db SPR_PAL_GREEN
	
	; 0x+4: SPRITE_KOGA
	db SPR_PAL_PURPLE
	
	; 0x+5: SPRITE_MISTY
	db SPR_PAL_ORANGE
	
	; 0x+6: SPRITE_SABRINA
	db SPR_PAL_PURPLE
	
	; 0x+7: SPRITE_SURGE
	db SPR_PAL_GREEN

	; 0x18: SPRITE_ROCKET
	db SPR_PAL_BROWN

	; 0x19: SPRITE_MEDIUM
	db SPR_PAL_RANDOM

	; 0x1a: SPRITE_WAITER
	db SPR_PAL_RANDOM

	; 0x1b: SPRITE_ERIKA
	db SPR_PAL_RANDOM

	; 0x1c: SPRITE_MOM_GEISHA
	db SPR_PAL_RANDOM

	; 0x1d: SPRITE_BRUNETTE_GIRL
	db SPR_PAL_RANDOM

	; 0x1e: SPRITE_LANCE
	db SPR_PAL_ORANGE

	; 0x1f: SPRITE_OAK_SCIENTIST_AIDE
	db SPR_PAL_BROWN

	; 0x20: SPRITE_OAK_AIDE
	db SPR_PAL_BROWN

	; 0x21: SPRITE_ROCKER ($20)
	db SPR_PAL_RANDOM

	; 0x22: SPRITE_SWIMMER
	db SPR_PAL_RANDOM

	; 0x23: SPRITE_WHITE_PLAYER
	db SPR_PAL_RANDOM

	; 0x24: SPRITE_GYM_HELPER
	db SPR_PAL_RANDOM

	; 0x25: SPRITE_OLD_PERSON
	db SPR_PAL_RANDOM

	; 0x26: SPRITE_MART_GUY
	db SPR_PAL_RANDOM

	; 0x27: SPRITE_FISHER
	db SPR_PAL_RANDOM

	; 0x28: SPRITE_OLD_MEDIUM_WOMAN
	db SPR_PAL_RANDOM

	; 0x29: SPRITE_NURSE
	db SPR_PAL_ORANGE

	; 0x2a: SPRITE_CABLE_CLUB_WOMAN
	db SPR_PAL_GREEN

	; 0x2b: SPRITE_MR_MASTERBALL
	db SPR_PAL_PURPLE

	; 0x2c: SPRITE_LAPRAS_GIVER
	db SPR_PAL_RANDOM

	; 0x2d: SPRITE_WARDEN
	db SPR_PAL_RANDOM

	; 0x2e: SPRITE_SS_CAPTAIN
	db SPR_PAL_RANDOM

	; 0x2f: SPRITE_FISHER2
	db SPR_PAL_RANDOM

	; 0x30: SPRITE_BLACKBELT
	db SPR_PAL_BROWN

	; 0x31: SPRITE_GUARD ($30)
	db SPR_PAL_BLUE

	; 0x32: $32
	db SPR_PAL_RANDOM

	; 0x33: SPRITE_MOM
	db SPR_PAL_ORANGE

	; 0x34: SPRITE_BALDING_GUY
	db SPR_PAL_RANDOM

	; 0x35: SPRITE_YOUNG_BOY
	db SPR_PAL_RANDOM

	; 0x36: SPRITE_GAMEBOY_KID
	db SPR_PAL_RANDOM

	; 0x37: SPRITE_GAMEBOY_KID_COPY
	db SPR_PAL_RANDOM

	; 0x38: SPRITE_CLEFAIRY
	db SPR_PAL_ORANGE

	; 0x39: SPRITE_AGATHA
	db SPR_PAL_BLUE

	; 0x3a: SPRITE_BRUNO
	db SPR_PAL_BROWN

	; 0x3b: SPRITE_LORELEI
	db SPR_PAL_ORANGE

	; 0x3c: SPRITE_SEEL
	db SPR_PAL_EMOJI

	; 0x-1: SPRITE_SANDSHREW
	db SPR_PAL_BROWN
	
	; 0x-2: SPRITE_ODDISH
	db SPR_PAL_GREEN
	
	; 0x-3: SPRITE_BULBASAUR
	db SPR_PAL_GREEN
	
	; 0x-4: SPRITE_OFFICER_JENNY
	db SPR_PAL_BLUE
	
	; 0x-5: SPRITE_CHANSEY
	db SPR_PAL_PURPLE
	
	; 0x-6: SPRITE_JIGGLYPUFF
	db SPR_PAL_PURPLE
	
	; 0x-7: SPRITE_PIKACHU
	db SPR_PAL_YELLOW
	
	; 0x-8: SPRITE_ARTICUNO
	db SPR_PAL_BLUE
	
	; 0x-9: SPRITE_ZAPDOS
	db SPR_PAL_YELLOW
	
	; 0x-A: SPRITE_MOLTRES
	db SPR_PAL_ORANGE
	
	; 0x-B: SPRITE_CUBONE
	db SPR_PAL_BROWN
		
	; 0x-C: SPRITE_DODUO
	db SPR_PAL_BROWN
	
	; 0x-D: SPRITE_FEAROW
	db SPR_PAL_BROWN
	
	; 0x-E: SPRITE_KANGASKHAN
	db SPR_PAL_BROWN
	
	; 0x-F: SPRITE_LAPRAS
	db SPR_PAL_BLUE
	
	; 0x-G: SPRITE_MACHOKE
	db SPR_PAL_BLUE
	
	; 0x-H: SPRITE_MACHOP
	db SPR_PAL_BLUE
	
	; 0x-I: SPRITE_MEOWTH
	db SPR_PAL_BROWN
	
	; 0x-J: SPRITE_NIDORANF
	db SPR_PAL_BLUE
	
	; 0x-K: SPRITE_NIDORANM
	db SPR_PAL_ORANGE
	
	; 0x-L: SPRITE_NIDORINO
	db SPR_PAL_ORANGE
	
	; 0x-M: SPRITE_PIDGEOT
	db SPR_PAL_BROWN
	
	; 0x-N: SPRITE_PIDGEY
	db SPR_PAL_BROWN
	
	; 0x-O: SPRITE_POLIWRATH
	db SPR_PAL_BLUE
	
	; 0x-P: SPRITE_PSYDUCK
	db SPR_PAL_YELLOW
	
	; 0x-Q: SPRITE_SLOWBRO
	db SPR_PAL_ORANGE
	
	; 0x-R: SPRITE_SLOWPOKE
	db SPR_PAL_ORANGE
	
	; 0x-S: SPRITE_SPEAROW
	db SPR_PAL_BROWN
	
	; 0x-T: SPRITE_WIGGLYTUFF
	db SPR_PAL_PURPLE
	
	; 0x-U: SPRITE_MEWTWO
	db SPR_PAL_PURPLE
	
	; 0x-V: SPRITE_MEW
	db SPR_PAL_PURPLE
	
	; 0x-W: SPRITE_WEEZING
	db SPR_PAL_PURPLE
	
	; 0x-X: SPRITE_HYPNO
	db SPR_PAL_YELLOW
	
	; 0x-Y: SPRITE_RATTATA
	db SPR_PAL_PURPLE
	
	; 0x-Z: SPRITE_OMANYTE
	db SPR_PAL_BLUE
	
	; 0x-#: SPRITE_WHIRLPOOL
	db SPR_PAL_EMOJI
	
	; 0x3d: SPRITE_BALL
	db SPR_PAL_ORANGE

	; 0x3e: SPRITE_OMANYTE
	db SPR_PAL_BROWN

	; 0x3f: SPRITE_BOULDER
	db SPR_PAL_HM

	; 0x40: SPRITE_PAPER_SHEET
	db SPR_PAL_BROWN

	; 0x41: SPRITE_BOOK_MAP_DEX
	db SPR_PAL_ORANGE

	; 0x42: SPRITE_CLIPBOARD
	db SPR_PAL_BROWN

	; 0x43: SPRITE_SNORLAX
	db SPR_PAL_GREEN

	; 0x44: SPRITE_OLD_AMBER_COPY
	db SPR_PAL_YELLOW

	; 0x45: SPRITE_OLD_AMBER
	db SPR_PAL_YELLOW

	; 0x46: SPRITE_LYING_OLD_MAN_UNUSED_1
	db SPR_PAL_BROWN

	; 0x47: SPRITE_LYING_OLD_MAN_UNUSED_2
	db SPR_PAL_BROWN

	; 0x48: SPRITE_LYING_OLD_MAN
	db SPR_PAL_BROWN

	assert_table_length NUM_SPRITES